#version: '3.9'

networks:
    tig-net:
        driver: bridge

volumes:
    tig-data:

services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: ""             # THIS WILL BE REPLACED
            INFLUXDB_ADMIN_USER: ""     # THIS WILL BE REPLACED
            INFLUXDB_ADMIN_PASSWORD: "" # THIS WILL BE REPLACED
        networks:
            - tig-net
        volumes:
            - tig-data:/var/lib/influxdb

    grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: "https://cscloud7-158.lnu.se/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "1234"
    networks:
      - tig-net
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

    telegraf:
        image: telegraf:latest
        depends_on:
            - "influxdb"
        environment:
            HOST_NAME: "telegraf"
            INFLUXDB_HOST: "influxdb"
            INFLUXDB_PORT: "8086"
            DATABASE: "" # THIS WILL BE REPLACED
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
        tty: true
        networks:
            - tig-net
        privileged: true

